### ISSUE TITLE
Can confirm that Arkham Knight is not supported

### ISSUE THREAD

**Issue by ClaimedInfinity** [UE-Explorer/UE-Explorer#63] opened 2024-08-07 00:08 UTC
It throws "Couldn't load or initialize package". Any more info needed?

**Comment by EliotVU** [comment] 2024-08-07 01:59
That's unfortunate, it should work since it was supported with UELib version 1.4 see https://github.com/EliotVU/Unreal-Library/issues/51

**Comment by ClaimedInfinity** [comment] 2024-08-07 23:54
Arkham City packages throw the same error. The same is with Aliens Colonial marines .upk files. Colonial Marines packages are not compressed.
Unreal, UT1, SWAT4 and Raven Shield .u files do work fine.
Could be that I'm doing something wrong? Maybe system or language settings? I'm decompressing a single package using: "decompress.exe -lzo <package name>" or "decompress.exe game=batman3/4 <package name>" then I try to open decompressed package with UEExplorer - and no luck.

![2024-08-08 021940](https://github.com/user-attachments/assets/a7ca92c0-b541-41ad-a6e7-8c81f234ec7f)

Also when opening a solution is VS2022. Could be something related?

![2024-08-08 030409](https://github.com/user-attachments/assets/61127598-9103-43b5-a614-21a04267f48e)
![2024-08-08 030456](https://github.com/user-attachments/assets/6d3f6713-3816-4132-b358-3c39814fe28b)

**Comment by EliotVU** [comment] 2024-08-08 23:15
Ah can confirm too, Knight and City do no longer work (regression) Asylum however appears to work fine.

**Comment by ClaimedInfinity** [comment] 2024-08-10 02:03
Yes, 1.3.1 (hotfix) is working for Arkham Knight

**Comment by EliotVU** [comment] 2024-08-13 03:23
Fixed, will be part of the next release.

**Closed as completed by EliotVU** 2024-08-13 03:23 UTC
Labels: bug, help wanted, UELib
