### ISSUE TITLE
No error crash opening borderlands 1 '.u' files

### ISSUE THREAD

**Issue by RedxYeti** [UE-Explorer/UE-Explorer#65] opened 2024-09-02 04:35 UTC
trying to open a borderlands 1 .u file will send the program into not responding.

I've uploaded a cooked file here if you want to try yourself.
https://github.com/RedxYeti/Yeti-BL2-SDK-Mods/blob/main/WillowGame.u

Borderlands 1 is ue3

**Comment by EliotVU** [comment] 2024-09-02 05:40
Duplicate of #55 Thanks though.

**Closed as completed by EliotVU** 2024-09-02 05:40 UTC
Labels: duplicate
